export const ADD_TODO = 'ADD_TODO';
export const UNKNOWN_ACTION = 'UNKNOWN_ACTION';
export const GET_STATE_IN_MIDDLE = 'GET_STATE_IN_MIDDLE';
export const SUBSCRIBE_IN_MIDDLE = 'SUBSCRIBE_IN_MIDDLE';
export const DISPATCH_IN_MIDDLE = 'DISPATCH_IN_MIDDLE';